### PR TITLE
Dataset blueprint

### LINKED ISSUE #8: Broken newer_url
Hi,
`newer_url` points to `/packages?id={{ id }}` instead of `/dataset/{{ id }}`.
CKAN 2.8.1.

### PR DESCRIPTION
**Pull request by frafra**
Fixes #8

### CODE REVIEW

**Comment by frafra** [comment]
The test is failing because of a PostgreSQL dependency, but that is not related with my commit.

**Comment by martinburchell** [comment]
Thanks for submitting this. I'll take a closer look soon.

I haven't checked to see if this would still be compatible with CKAN 2.5. If not, we need to think about development branches for different versions as we still have a client on 2.5.

**Comment by frafra** [comment]
It will not, because the change happened less than one year ago (see https://github.com/ckan/ckan/commit/833abc327f86f960dd3f62efe7a0a151d046a975).
I pushed to master because that is the branch used for most recent/unstable code usually, but feel free to do as you please, of course.

**Comment by martinburchell** [comment]
Thanks @frafra . I've created a 2.5 development branch should we need to make any further changes for that version.

**Comment by frafra** [comment]
I am sorry, it is not CKAN 2.8.1, but the master version. This patch should be reverted for 2.8.
This is happened because CKAN Docker images are not tagged, so I was running a more recent version (I am taking care of that) and the tests for ckanext-datasetversions are not working at the moment.

**Comment by martinburchell** [comment]
Thanks for letting us know. We're likely to be testing this plugin with later versions of CKAN in the coming weeks and we'll be able to give this some more attention around then. Thanks for all your contributions to date!

**Pull request merged**
