### PR TITLE
Support private dataset versions

### LINKED ISSUE #12: Versions ignored if private
Private datasets representing versions are not shown in the "Versions" widget nor the notification that your dataset has been superseded by a new one appears, even if the user is allowed to access to them.

### PR DESCRIPTION
**Pull request by frafra**
Fixes #12

### CODE REVIEW

**Comment by frafra** [comment]
There is an issue at the moment: guests cannot access to the latest package using the URL without specifying the version:

```python-traceback
File '/usr/lib/ckan/venv/src/ckan/ckan/controllers/package.py', line 401 in read
  context, {'id': resource['id']})
File '/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py', line 464 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/venv/src/ckan/ckan/logic/action/get.py', line 1139 in resource_view_list
  _check_access('resource_view_list', context, data_dict)
File '/usr/lib/ckan/venv/src/ckan/ckan/logic/__init__.py', line 306 in check_access
  raise NotAuthorized(msg)
NotAuthorized: User  not authorized to read resource f72292e5-04e1-41ff-92c4-64aa9dca6b25
```

**Comment by frafra** [comment]
I have been using this patch in production for quite a while now, without any major issue.

**Comment by frafra** [comment]
Merged and squashed in b753465f3ae74be0ac3d75aa8afef9286b3851f8.
Let me know if there is anything else that should be changed/improved :)

**Comment by martinburchell** [comment]
@frafra really happy for you to merge anything you find useful

**Pull request merged**
